name: Run Docker in GitHub Actions

on: push  # Runs on every push to the repository

jobs:
  run-docker:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Get your repository's code

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Run Docker Container
        run: docker run my-app
