name: Build and Run Docker

on: push

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create service account file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > data-project-452300-e2c341ffd483.json

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Run Docker Container with Service Account
        run: docker run -v $PWD/data-project-452300-e2c341ffd483.json:/app/data-project-452300-e2c341ffd483.json my-app
