name: Build and Run Docker App

on: push  # Runs on every push

jobs:
  run-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create service account file from secret
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > data-project-452300-e2c341ffd483.json

      - name: Build Docker Image
        run: docker build -t my-app .

      - name: Run Docker Container and Execute Application
        run: |
          docker run --rm \
            -v $PWD/data-project-452300-e2c341ffd483.json:/app/data-project-452300-e2c341ffd483.json \
            -e GOOGLE_APPLICATION_CREDENTIALS="/app/data-project-452300-e2c341ffd483.json" \
            my-app
